### ISSUE TITLE
Clicking "Create Account" on the homepage opens the auth modal with "Login" tab selected.

### ISSUE THREAD

**Issue by mojombo** [redwoodjs/repeater-issues#2]
I would expect it to open with the "Sign Up" tab selected.

**Comment by cannikin** [comment]
We should be able to expand on Netlify provider in `redwoodjs/auth` to give us access to the widget's `open('signup')` and destructure a `signUp` from `useAuth()` just like we destructure `logIn` to call `open('login')`: https://github.com/redwoodjs/redwood/blob/main/packages/auth/src/authClients/netlify.ts#L14

**Comment by cannikin** [comment]
I was able to do this by calling `netlifyIdentity` manually since it's not exposed through @redwoodjs/auth yet:

    netlifyIdentity.open('signup')
