### ISSUE TITLE
run_at timestamp

### ISSUE THREAD

**Issue by dnprock** [redwoodjs/repeater-issues#4]
Hi Rob,

I'm trying repeater.dev. I set a job's timestamp to the format specified in the Docs. It's giving me an error.

"GraphQL error: run_at is not a valid ISO8601 Datetime"

I attach the screenshot.

![Screen Shot 2020-10-14 at 11 13 50 AM](https://user-images.githubusercontent.com/497205/96028850-b5f51180-0e0e-11eb-9c99-a87a79eef29d.png)

Phuoc Do

**Comment by cannikin** [comment]
Which browser is this? That `run_at` field should be a datetime picker, per the HTML5 input spec, but it looks like it's not supported in that browser...

![image](https://user-images.githubusercontent.com/300/96030245-9f4fba00-0e10-11eb-8ea1-b9544201edcf.png)

**Comment by cannikin** [comment]
But it should definitely fall back to letting you enter ISO8601 format if the picker isn't supported! I'll fix it!

**Comment by cannikin** [comment]
@dnprock I just pushed a fix, can you try again?

**Comment by dnprock** [comment]
@cannikin thanks, I was using Safari. I switch to Chrome and see the date picker now. I created a job. It'd be nice to have a manual run button so I can check the result right away. Also, is there a way to Edit or Delete and an existing job?

**Comment by cannikin** [comment]
Edit, Delete and Run Now are all on my list to build soon!
