### ISSUE TITLE
Is the app down?

### ISSUE THREAD

**Issue by BrandonNoad** [redwoodjs/repeater-issues#9]
Hi. My job stopped working, so I went to the app to debug, but I can't get past the landing page.

It says I'm logged in, but I'm getting a 500 internal server error for `POST https://api.repeater.dev/graphql {query: "query __REDWOOD__AUTH_GET_CURRENT_USER { redwood { currentUser } }"}`

**Comment by cannikin** [comment]
Hi @BrandonNoad Sorry about that, try now?

**Comment by BrandonNoad** [comment]
Yes, it working again. Thanks @cannikin 🙏
